// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: rpc_im.proto

package server

import (
	"context"

	"im/rpc_im/internal/logic/imservice"
	"im/rpc_im/internal/svc"
	"im/rpc_im/pb"
)

type ImServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedImServiceServer
}

func NewImServiceServer(svcCtx *svc.ServiceContext) *ImServiceServer {
	return &ImServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ImServiceServer) Login(ctx context.Context, in *pb.LoginRequest) (*pb.LoginResponse, error) {
	l := imservicelogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *ImServiceServer) Logout(ctx context.Context, in *pb.LogoutRequest) (*pb.LogoutResponse, error) {
	l := imservicelogic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}

func (s *ImServiceServer) PostMessage(ctx context.Context, in *pb.PostMsg) (*pb.PostResponse, error) {
	l := imservicelogic.NewPostMessageLogic(ctx, s.svcCtx)
	return l.PostMessage(in)
}
